const Symptoms = [
  "acidity",
  "back_pain",
  "bladder_discomfort",
  "breathlessness",
  "burning_micturition",
  "chills",
  "constipation",
  "continuous_sneezing",
  "cough",
  "cramps",
  "fatigue",
  "headache",
  "high_fever",
  "indigestion",
  "joint_pain",
  "mood_swings",
  "muscle_wasting",
  "muscle_weakness",
  "neck_pain",
  "pain_during_bowel_movements",
  "patches_in_throat",
  "pus_filled_pimples",
  "shivering",
  "skin_rash",
  "stiff_neck",
  "stomach_pain",
  "sunken_eyes",
  "vomiting",
  "weakness_in_limbs",
  "weight_gain",
  "weight_loss",
  "yellowish_skin",
  "itching",
  "abdominal_pain",
  "anxiety",
  "blackheads",
  "blister",
  "cold_hands_and_feets",
  "continuous_feel_of_urine",
  "dark_urine",
  "dehydration",
  "dizziness",
  "foul_smell_of urine",
  "hip_joint_pain",
  "knee_pain",
  "lethargy",
  "loss_of_appetite",
  "loss_of_balance",
  "nausea",
  "nodal_skin_eruptions",
  "pain_in_anal_region",
  "red_sore_around_nose",
  "restlessness",
  "scurring",
  "silver_like_dusting",
  "skin_peeling",
  "spinning_movements",
  "swelling_joints",
  "ulcers_on_tongue",
  "watering_from_eyes",
  "weakness_of_one_body_side",
  "altered_sensorium",
  "bloody_stool",
  "blurred_and_distorted_vision",
  "distention_of_abdomen",
  "excessive_hunger",
  "extra_marital_contacts",
  "family_history",
  "history_of_alcohol_consumption",
  "inflammatory_nails",
  "internal_itching",
  "irregular_sugar_level",
  "irritation_in_anus",
  "lack_of_concentration",
  "loss_of_balance",
  "mucoid_sputum",
  "painful_walking",
  "passage_of_gases",
  "small_dents_in_nails",
  "spotting_ urination",
  "stomach_pain",
  "sweating",
  "swelling_of_stomach",
  "swollen_legs",
  "unsteadiness",
  "yellow_crust_ooze",
  "yellowing_of_eyes",
  "brittle_nails",
  "drying_and_tingling_lips",
  "enlarged_thyroid",
  "increased_appetite",
  "irritability",
  "prominent_veins_on_calf",
  "puffy_face_and_eyes",
  "yellow_urine",
  "pain_behind_the_eyes",
  "polyuria",
  "slurred_speech",
  "swollen_extremeties",
  "throat_irritation",
  "toxic_look_(typhos)",
  "visual_disturbances",
  "acute_liver_failure",
  "belly_pain",
  "coma",
  "palpitations",
  "receiving_blood_transfusion",
  "receiving_unsterile_injections",
  "redness_of_eyes",
  "rusty_sputum",
  "sinus_pressure",
  "abnormal_menstruation",
  "malaise",
  "runny_nose",
  "stomach_bleeding",
  "phlegm",
  "congestion",
  "red_spots_over_body",
  "chest_pain",
  "blood_in_sputum",
  "loss_of_smell",
  "muscle_pain"
];
const arSymptoms =
[
   "حموضة",
   "ألم في الظهر",
   "اضطراب_المثانة",
   "ضيق التنفس",
   "حرق_التبول",
   "قشعريرة",
   "إمساك",
   "العطس_المستمر",
   "سعال",
   "تشنجات",
   "تعب",
   "صداع",
   "ارتفاع درجة الحرارة",
   "عسر الهضم",
   "الم المفاصل",
   "تقلب المزاج",
   "الهزال العضلي",
   "ضعف_العضلات",
   "الم الرقبة",
   "ألم_أثناء_حركات_الأمعاء",
   "بقع_في_الحلق",
   "البثور_المملوءة بالقيح",
   "يرتجف",
   "الطفح الجلدي",
   "تصلب الرقبة",
   "آلام_المعدة",
   "العيون الغارقة",
   "القيء",
   "الضعف_في_الأطراف",
   "زيادة الوزن",
   "فقدان الوزن",
   "جلد مصفر",
   "مثير للحكة",
   "وجع بطن",
   "قلق",
   "الرؤوس السوداء",
   "بثرة",
   "الأيدي_الباردة_والقدمين",
   "الشعور المستمر بالبول",
   "البول الداكن",
   "تجفيف",
   "دوخة",
   "رائحة البول كريهة",
   "ألم_مفاصل_الورك",
   "ألم الركبة",
   "الخمول",
   "فقدان الشهية",
   "فقدان التوازن",
   "غثيان",
   "الثوران_العقدي_الجلدي",
   "ألم_في_منطقة_الشرج",
   "تقرحات حمراء حول الأنف",
   "الأرق",
   "الضرب",
   "فضة_مثل_غبار",
   "تقشير_الجلد",
   "حركات_الغزل",
   "تورم_المفاصل",
   "قرحة_اللسان",
   "يسقي_من_العيون",
   "ضعف_جانب_الجسم",
   "مستشعر_متغير",
   "براز مدمي",
   "الرؤية غير الواضحة والمشوهة",
   "انتفاخ_البطن",
   "الجوع_المفرط",
   "اتصالات_زواجية إضافية",
   "تاريخ العائلة",
   "تاريخ_استهلاك_الكحول",
   "التهاب_الأظافر",
   "حكة_داخلية",
   "مستوى_السكر غير المنتظم",
   "تهيج_في_الشرج",
   "نقص_التركيز",
   "فقدان التوازن",
   "البلغم المخاطي",
   "المشي_المؤلم",
   "ممر_الغازات",
   "small_dents_in_nails",
   "اكتشاف_التبول",
   "آلام_المعدة",
   "التعرق",
   "تورم_المعدة",
   "تورم_الساقين",
   "عدم الثبات",
   "قشرة صفراء",
   "اصفرار_العيون",
   "أظافر هشة",
   "تجفيف_وتنميل_الشفاه",
   "تضخم_الغدة الدرقية",
   "زيادة الشهية",
   "التهيج",
   "الأوردة البارزة_على_كالف",
   "الوجه المنتفخ والعيون",
   "البول الأصفر",
   "ألم خلف العيون",
   "بولوريا",
   "كلام غير واضح",
   "الأطراف_المتورمة",
   "تهيج الحلق",
   "tox_look_(التيفوس)",
   "اضطرابات بصرية",
   "فشل الكبد الحاد",
   "ألم_البطن",
   "غيبوبة",
   "خفقان",
   "استقبال_نقل الدم",
   "تلقي_الحقن_غير_المعقمة",
   "احمرار_العيون",
   "البلغم الصدئ",
   "ضغط الجيوب الأنفية",
   "الحيض_غير الطبيعي",
   "توعك",
   "سيلان الأنف",
   "نزيف_المعدة",
   "البلغم",
   "ازدحام",
   "البقع الحمراء_فوق_الجسم",
   "ألم صدر",
   "الدم_في_البلغم",
   "فقدان_الرائحة",
   "ألم عضلي"
];


export  {Symptoms, arSymptoms};